version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ivan
      POSTGRES_USER: ivan
      POSTGRES_DB: pomky
    ports: 
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080